---
- name: check if local configuration exists
  stat:
    path: "{{ certbot_conf_dir }}"
  register: d1
  delegate_to: localhost

- name: restore configuration
  include_role:
    name: certbot_common
    tasks_from: restore
  delegate_to: localhost
  when:
    - d1.stat.isdir is not defined or not d1.stat.isdir

- name: fix local configuration permissions
  include_role:
    name: certbot_common
    tasks_from: permissions
  delegate_to: localhost
  when:
    - d1.stat.isdir is defined
    - d1.stat.isdir

- name: stat cert
  stat:
    path: "{{ certbot_cert_path }}"
  register: d2
  delegate_to: localhost

- name: deploy certificates
  copy:
    src: "{{ certbot_cert_path }}"
    dest: "/etc/ssl/certs/{{ certbot_cert_name }}.pem"
    mode: 0644
  notify:
    - reload nginx
  when:
    - d2.stat.exists is defined

- name: deploy private key
  copy:
    src: "{{ certbot_key_path }}"
    dest: "/etc/ssl/private/{{ certbot_cert_name }}.key"
    mode: 0640
  notify:
    - reload nginx
  when:
    - d2.stat.exists is defined
