---
- name: add keepalived PPA
  apt_repository: repo=ppa:keepalived/stable

- name: Install keepalived
  apt: name=keepalived state=latest

- name: Install check script
  copy: >
    src=chk_mysql_port.sh
    dest=/etc/keepalived/chk_mysql_port.sh
    mode=0775

- name: Configure keepalived
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf

- name: Restart keepalived
  systemd:
    name: keepalived
    state: restarted

- name: Pause for 5 seconds
  pause:
    seconds: 5

- name: Restart one instance
  systemd:
    name: keepalived
    state: restarted
  run_once: true
